apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: web-spanischlehrerdeutsch
  namespace: spanischlehrerdeutsch-production
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image-repository.yaml
  - image-policy.yaml
  - image-automation.yaml
